## Configuration file for ClubappServer application.

# Server configuration.
server:
  applicationConnectors:
    - type: http
      port: 8080
    #- type: https
    #  keyStorePassword: KEYSTOREPW
    #  keyStorePath: keystore.jks
    #  port: 8443
    #  validateCerts: false

# Logging configuration.
logging:
  # Permit DEBUG, INFO, WARN and ERROR messages to be logged by appenders.
  level: INFO

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: ${DBUSER}
    # the password
    password: ${DBPW}
    # the JDBC URL
    url: jdbc:mysql://${DBURL}
    # any properties of JDBC driver
    properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MySQLDialect