package de.hummelflug.clubapp.server.core;

import java.util.HashSet;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SecondaryTable;
import javax.persistence.SecondaryTables;
import javax.persistence.Table;

import de.hummelflug.clubapp.server.utils.GenderType;

import static com.google.common.base.Preconditions.checkNotNull;

@Entity
@Table(name = "team")
@SecondaryTables({
	@SecondaryTable(name = "club_team",
			pkJoinColumns=@PrimaryKeyJoinColumn(name="team_id", referencedColumnName="id")),
	@SecondaryTable(name = "department_team",
			pkJoinColumns=@PrimaryKeyJoinColumn(name="team_id", referencedColumnName="id")),
	@SecondaryTable(name = "team_schedule",
			pkJoinColumns=@PrimaryKeyJoinColumn(name="team_id", referencedColumnName="id"))
})
@NamedQueries({
    @NamedQuery(name = "de.hummelflug.clubapp.server.core.Team.findAll",
            query = "select t from Team t"),
    @NamedQuery(name = "de.hummelflug.clubapp.server.core.Team.findByName",
            query = "select t from Team t "
            + "where t.name like :name ")
})
public class Team extends AbstractModel {
	
	@Column(name = "creator_user_id", nullable = false)
	private Long creatorUserId;
	
	@Column(table = "club_team", name = "club_id", nullable = false)
	private Long clubId;
	
	@Column(table = "department_team", name = "department_id", nullable = false)
	private Long departmentId;
	
	@Column(name = "name", nullable = false)
	private String name;
	
	@Column(name = "gender", nullable = false)
	@Enumerated(EnumType.STRING)
	private GenderType gender;
	
	@Column(name = "age_class", nullable = false)
	private Integer ageClass;
	
	@Column(name = "sport_type_id", nullable = false)
	private Long sportTypeId;
	
	@ElementCollection
	@CollectionTable(name = "team_member", joinColumns = @JoinColumn(name = "team_id"))
	@Column(name = "member_user_id", nullable = false)
	private Set<Long> members;
	
	@ElementCollection
	@CollectionTable(name = "coach_current_team", joinColumns = @JoinColumn(name = "team_id"))
	@Column(name = "coach_id", nullable = false)
	private Set<Long> coaches;
	
	@ElementCollection
	@CollectionTable(name = "player_current_team", joinColumns = @JoinColumn(name = "team_id"))
	@Column(name = "player_id", nullable = false)
	private Set<Long> players;
	
	@Column(table = "team_schedule", name = "schedule_id", nullable = false)
	private Long teamScheduleId;
	
	@ElementCollection
	@CollectionTable(name = "team_news_content", joinColumns = @JoinColumn(name = "team_id"))
	@Column(name = "news_content_id", nullable = false)
	private Set<Long> news;
	
	/**
	 * A no-argument constructor
	 */
	public Team() {
		coaches = new HashSet<Long>();
		members = new HashSet<Long>();
		news = new HashSet<Long>();
		players = new HashSet<Long>();
	}
	
	/**
     * A constructor to create a user. id, creationTime, lastModification is not passed, cause it's
     * auto-generated by RDBMS.
     * 
     * @param creatorUserId user id of creator
     * @param name name of the team
     * @param gender gender of the team
     * @param ageClass age class of the team
     * @param sportTypeId id of sport type
     */
	public Team(@Nonnull Long creatorUserId, @Nonnull String name, GenderType gender, @Nonnull Integer ageClass,
			@Nonnull Long sportTypeId) {
		coaches = new HashSet<Long>();
		members = new HashSet<Long>();
		news = new HashSet<Long>();
		players = new HashSet<Long>();
		
		this.creatorUserId = checkNotNull(creatorUserId, "creator user id cannot be null");
		this.name = checkNotNull(name, "name cannot be null");
		this.gender = gender;
		this.ageClass = checkNotNull(ageClass, "age class cannot be null");
		this.sportTypeId = checkNotNull(sportTypeId, "sport type id cannot be null");
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((ageClass == null) ? 0 : ageClass.hashCode());
		result = prime * result + ((clubId == null) ? 0 : clubId.hashCode());
		result = prime * result + ((coaches == null) ? 0 : coaches.hashCode());
		result = prime * result + ((creatorUserId == null) ? 0 : creatorUserId.hashCode());
		result = prime * result + ((departmentId == null) ? 0 : departmentId.hashCode());
		result = prime * result + ((gender == null) ? 0 : gender.hashCode());
		result = prime * result + ((members == null) ? 0 : members.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((news == null) ? 0 : news.hashCode());
		result = prime * result + ((players == null) ? 0 : players.hashCode());
		result = prime * result + ((sportTypeId == null) ? 0 : sportTypeId.hashCode());
		result = prime * result + ((teamScheduleId == null) ? 0 : teamScheduleId.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		Team other = (Team) obj;
		if (ageClass == null) {
			if (other.ageClass != null)
				return false;
		} else if (!ageClass.equals(other.ageClass))
			return false;
		if (clubId == null) {
			if (other.clubId != null)
				return false;
		} else if (!clubId.equals(other.clubId))
			return false;
		if (coaches == null) {
			if (other.coaches != null)
				return false;
		} else if (!coaches.equals(other.coaches))
			return false;
		if (creatorUserId == null) {
			if (other.creatorUserId != null)
				return false;
		} else if (!creatorUserId.equals(other.creatorUserId))
			return false;
		if (departmentId == null) {
			if (other.departmentId != null)
				return false;
		} else if (!departmentId.equals(other.departmentId))
			return false;
		if (gender != other.gender)
			return false;
		if (members == null) {
			if (other.members != null)
				return false;
		} else if (!members.equals(other.members))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (news == null) {
			if (other.news != null)
				return false;
		} else if (!news.equals(other.news))
			return false;
		if (players == null) {
			if (other.players != null)
				return false;
		} else if (!players.equals(other.players))
			return false;
		if (sportTypeId == null) {
			if (other.sportTypeId != null)
				return false;
		} else if (!sportTypeId.equals(other.sportTypeId))
			return false;
		if (teamScheduleId == null) {
			if (other.teamScheduleId != null)
				return false;
		} else if (!teamScheduleId.equals(other.teamScheduleId))
			return false;
		return true;
	}

	/**
	 * @return the creatorUserId
	 */
	public Long getCreatorUserId() {
		return creatorUserId;
	}

	/**
	 * @param creatorUserId the creatorUserId to set
	 */
	public void setCreatorUserId(Long creatorUserId) {
		this.creatorUserId = creatorUserId;
	}

	/**
	 * @return the clubId
	 */
	public Long getClubId() {
		return clubId;
	}

	/**
	 * @param clubId the clubId to set
	 */
	public void setClubId(Long clubId) {
		this.clubId = clubId;
	}

	/**
	 * @return the departmentId
	 */
	public Long getDepartmentId() {
		return departmentId;
	}

	/**
	 * @param departmentId the departmentId to set
	 */
	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the gender
	 */
	public GenderType getGender() {
		return gender;
	}

	/**
	 * @param gender the gender to set
	 */
	public void setGender(GenderType gender) {
		this.gender = gender;
	}

	/**
	 * @return the ageClass
	 */
	public Integer getAgeClass() {
		return ageClass;
	}

	/**
	 * @param ageClass the ageClass to set
	 */
	public void setAgeClass(Integer ageClass) {
		this.ageClass = ageClass;
	}

	/**
	 * @return the sportTypeId
	 */
	public Long getSportTypeId() {
		return sportTypeId;
	}

	/**
	 * @param sportTypeId the sportTypeId to set
	 */
	public void setSportTypeId(Long sportTypeId) {
		this.sportTypeId = sportTypeId;
	}

	/**
	 * @return the members
	 */
	public Set<Long> getMembers() {
		return members;
	}

	/**
	 * @param members the members to set
	 */
	public void setMembers(Set<Long> members) {
		this.members = members;
	}

	/**
	 * @return the coaches
	 */
	public Set<Long> getCoaches() {
		return coaches;
	}

	/**
	 * @param coaches the coaches to set
	 */
	public void setCoaches(Set<Long> coaches) {
		this.coaches = coaches;
	}

	/**
	 * @return the players
	 */
	public Set<Long> getPlayers() {
		return players;
	}

	/**
	 * @param players the players to set
	 */
	public void setPlayers(Set<Long> players) {
		this.players = players;
	}

	/**
	 * @return the teamScheduleId
	 */
	public Long getTeamScheduleId() {
		return teamScheduleId;
	}

	/**
	 * @param teamScheduleId the teamScheduleId to set
	 */
	public void setTeamScheduleId(Long teamScheduleId) {
		this.teamScheduleId = teamScheduleId;
	}

	/**
	 * @return the news
	 */
	public Set<Long> getNews() {
		return news;
	}

	/**
	 * @param news the news to set
	 */
	public void setNews(Set<Long> news) {
		this.news = news;
	}
	
}
